# 此开源项目地址 https://github.com/lowlighter/metrics

name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # 基础信息
      - name: base
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/base.svg
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          user: hash-panda
          template: classic
          config_timezone: Asia/Beijing
          base: "header, activity, repositories"
